language: node_js
node_js: stable
branches:
  only:
  - source

install: npm install
before_install:
- git submodule update --init --remote --recursive
before_script:
- git config --global user.name "iamkots"
- git config --global user.email "kotskute@gmail.com"
- sed -i "s/__GITHUB_TOKEN__/${__GITHUB_TOKEN__}/" _config.yml

script: npm run build